eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8000/eureka/ #配置注册中心地址

server:
  port: 9000

spring:
  application:
    name: shop-gateway
zuul:
  routes:
    shop-cloud-cate:
     path: /cate/**
    shop-cloud-goods:
     path: /goods/**
    shop-cloud-member:
     path: /member/**
    shop-cloud-cart:
     path: /cart/**

fh:
  shop:
    checkUrls: /api/findMember,/api/logOut,/api/addCart,/api/findCart,/api/findCartCount,/api/deleteCartItem,/api/deleteBatch
